# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Sia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sia
  pod 'OrkaPreviewData'
  pod 'OrkaApiRouter', :git => 'https://github.com/joey-barbier/ios-apiRouter.git'

  target 'SiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SiaUITests' do
    # Pods for testing
  end

end
